[package]
name = "noop-nrelay-wstd"
version = "0.0.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
serde_json = "1.0.145"
valq = "0.1.0"
wstd = { version = "0.6.3", default-features = false }
wstd-tungstenite = { version = "0.2.2", default-features = false, features = ["handshake"] }
